baseURL: https://farsitest98.pages.dev
languageCode: 'fa'
defaultContentLanguage: 'fa'
title: 'یک قالب وبلاگ'
theme: "PaperMod"

pagination:
  pagerSize: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

publishDir: "public"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "خانه"
    icon: /apple-touch-icon.png
    iconHeight: 35

  profileMode:
    enabled: false

  homeInfoParams:
    Title: سلام
    Content: >
      سلام اینجا قدری درباره همه چیز می‌نویسم

  socialIcons:
    - name: twitter
      url: "https://twitter.com/pourmand_amir"
    - name: stackoverflow
      url: "https://stackoverflow.com/"
    - name: github
      url: "https://github.com/pourmand1376"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  editPost:
    URL: ""
    Text: ""
    appendFilePath: false

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false

permalinks:
  posts: "/:contentbasename/"

menu:
  main:
    - identifier: FATags
      name: تگ‌ها
      url: /fatags/
      weight: 20
    - identifier: archives
      name: آرشیو
      url: /archives/
      weight: 30

languages:
  fa:
    languageName: "farsi"
    weight: 1
    languagedirection: rtl
    taxonomies:
      category: categories
      tag: fatags
      series: series
